---
- name: Prepare hosts
  hosts: all
  roles:
    - role: ansible-loki
      vars:
        loki_version: 1.6.1
  pre_tasks:
  - name: Install unzip
    package:
      disablerepo: epel
      name:
        - unzip
