---
kind: pipeline
name: default

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  base: /ansible-loki

steps:
  - name: molecule test
    image: quay.io/ansible/molecule:2.22
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      MOLECULE_NO_LOG: no
      NETRC: "" # drone automatically sets up .netrc for github login
                # but that breaks the loki/promtail release downloads 
    commands:
      - molecule test
