---
# FIXME: check version
- name: check if local loki download exists
  stat:
    path: "/tmp/{{ __loki_archive }}"
  register: loki_exists

- block:
    - name: Download loki release
      become: false
      get_url:
        url: "{{ __loki_download }}"
        dest: "/tmp/{{ __loki_archive }}"
        checksum: "sha256:{{ __loki_download_github }}/{{ loki_version }}/SHA256SUMS"
      register: _download_release
      until: _download_release is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack loki release
      become: false
      unarchive:
        src: "/tmp/{{ __loki_archive }}"
        dest: "/tmp"
        creates: "/tmp/loki-{{ __loki_go_os }}-{{ __loki_go_arch }}"
      delegate_to: localhost
      check_mode: false
  when: not loki_exists.stat.exists

- name: Distribute loki to servers
  copy:
    src: "/tmp/loki-{{ __loki_go_os }}-{{ __loki_go_arch }}"
    dest: "/usr/local/bin/loki"
    mode: 0755
    owner: root
    group: root
  notify: restart loki
  when: not ansible_check_mode
