---
- import_tasks: preflight.yml

- name: Install loki
  include_tasks: loki.yml
  when: __install_loki

- name: Install promtail
  include_tasks: promtail.yml
  when:
    - __install_promtail
    - not promtail_use_docker

- name: Install promtail [Docker]
  include_tasks: promtail-docker.yml
  when:
    - __install_promtail
    - promtail_use_docker
