---
- name: Install systemd-unit
  template:
    src: "systemd-{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
  with_items: '{{ loki_parts_to_install }}'
  notify:
    - reload systemd
  when: "__loki_go_os == 'linux'"

- name: Create config directories for loki
  file:
    mode: '0755'
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ loki_config_directory }}"
    - "{{ loki_config_store }}"
  when: __install_loki

- name: Create config directories for promtail
  file:
    mode: '0755'
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ promtail_config_directory }}"
    - /var/lib/promtail
  when: __install_promtail

- name: Setup configuration
  template:
    src: "{{ item }}.yml.j2"
    dest: "/etc/{{ item }}/{{ item }}.yml"
    mode: '0644'
  with_items: "{{ loki_parts_to_install }}"
  notify:
    - restart systemd units

- name: Install loki
  include_tasks: loki.yml
  when: __install_loki

- name: Install promtail
  include_tasks: promtail.yml
  when: __install_promtail
