---
- name: reload systemd
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
  with_items: '{{ loki_parts_to_install }}'

- name: restart systemd units
  service:
    name: "{{ item }}"
    state: restarted
  with_items: '{{ loki_parts_to_install }}'
