---
- name: Converge
  hosts: loki
  roles:
    - role: ansible-loki
      vars:
        loki_parts_to_install:
          - loki

- name: Converge
  hosts: promtail
  roles:
    - role: ansible-loki
      vars:
        loki_parts_to_install:
            - promtail
